#!/bin/bash

: "${VERSION?You have to specify the artifact VERSION. Example: VERSION=0.0.4 ./deploy/build-prod}"

VERSION=$VERSION \
  TARGET=prod \
  SEVSEC_API_URL=https://donandoapp-fe.com \
  ./deploy/build
