
# basic information for generating and executing this definition
SenzaInfo:
  StackName: donandoapp-fe
  Parameters:
    - ImageVersion:
        Description: "Docker image version of donandoapp-fe."

# a list of senza components to apply to the definition
SenzaComponents:

  # this basic configuration is required for the other components
  - Configuration:
      Type: Senza::StupsAutoConfiguration # auto-detect network setup

  # will create a launch configuration and auto scaling group with scaling triggers
  - AppServer:
      Type: Senza::TaupageAutoScalingGroup
      InstanceType: t2.small
      SecurityGroups:
        - app-donandoapp-fe
      IamRoles:
        - app-donandoapp-fe
      ElasticLoadBalancer: AppLoadBalancer
      AssociatePublicIpAddress: false # change for standalone deployment in default VPC
      TaupageConfig:
        application_version: "{{Arguments.ImageVersion}}"
        runtime: Docker
        source: "pierone.stups.zalan.do/labs/donandoapp-fe-prod:{{Arguments.ImageVersion}}"
        health_check_path: /
        ports:
          8080: 8080
        mint_bucket: "zalando-stups-mint-288593816804-eu-west-1"
        root: true

  # creates an ELB entry and Route53 domains to this ELB
  - AppLoadBalancer:
      Type: Senza::WeightedDnsElasticLoadBalancer
      HTTPPort: 8080
      HealthCheckPath: /
      SecurityGroups:
        - app-donandoapp-fe-lb
      Scheme: internet-facing
