
# basic information for generating and executing this definition
SenzaInfo:
  StackName: donandoapp-fe
  Parameters:
    - ImageVersion:
        Description: "Docker image version of donandoapp-fe."

# a list of senza components to apply to the definition
SenzaComponents:

  # this basic configuration is required for the other components
  - Configuration:
      Type: Senza::StupsAutoConfiguration # auto-detect network setup

  # will create a launch configuration and auto scaling group with scaling triggers
  - AppServer:
      Type: Senza::TaupageAutoScalingGroup
      InstanceType: t2.micro
      SecurityGroups:
        - app-donandoapp-fe
      IamRoles:
        - app-donandoapp-fe
      ElasticLoadBalancer: AppLoadBalancer
      AssociatePublicIpAddress: false # change for standalone deployment in default VPC
      TaupageConfig:
        application_version: "{{Arguments.ImageVersion}}"
        runtime: Docker
        source: "pierone.stups.zalan.do/labs/donandoapp-fe-prod:{{Arguments.ImageVersion}}"
        health_check_path: /
        ports:
          8080: 8080
          8181: 8181
        mint_bucket: "zalando-stups-mint-288593816804-eu-central-1"
        root: true

  # creates an ELB entry and Route53 domains to this ELB
  - AppLoadBalancer:
      Type: Senza::WeightedDnsElasticLoadBalancer
      HTTPPort: 8080
      HealthCheckPath: /
      SecurityGroups:
        - app-donandoapp-fe-lb
      Scheme: internet-facing
      Listeners:
      - InstancePort: 8080
        LoadBalancerPort: 443
        InstanceProtocol: HTTP
        Protocol: HTTPS
        SSLCertificateId: "arn:aws:acm:eu-central-1:288593816804:certificate/c8de68fa-2b0e-4b48-b1e5-836ff9158bac"
      - InstancePort: 8181
        LoadBalancerPort: 80
        InstanceProtocol: HTTP
        Protocol: HTTP
