#!/bin/bash

: "${VERSION?You have to specify the artifact VERSION}"
: "${TARGET?You have to specify a TARGET}"

# push docker image using tag -- $VERSION
docker push pierone.stups.zalan.do/labs/donandoapp-fe-$TARGET:$VERSION

STACK_VERSION=${VERSION//./}

echo "Next step:"
echo "=> senza create ./deploy/donandoapp-fe-$TARGET.yaml --region eu-central-1 $STACK_VERSION $VERSION"
